### PR TITLE
Fix for PartialContinuation issues highlighted by Seaside tests

### PR DESCRIPTION
**Pull request by rko281**
Fix an issue highlighted by Seaside SUnit tests WAPartialContinuationTest>>testMarkerOnValue (included here as PartialContinuationTest>>testMarkerOnValueDiscardingResult) and WAFlowPlatformTest>>testSuspendCallbackDo (not included due to Seaside dependencies).
Also:
 - reinstate missing method Process>>stackFramesFrom:depth:
 - minor refactoring for easier subclassing in Seaside
 - move test class into separate package to avoid creating dependency on SUnit package

### CODE REVIEW

**Comment by fxgallego** [comment]
Sorry I didn't see this before. This package is a prerequisite for you Seaside port or it's is bundled in your repo?

**Comment by rko281** [comment]
I included the package in my my Seaside repo, partly due to this change still being pending at the time but also for convenience, i.e. so Seaside can be downloaded and installed from a single repository. 

I'm no git(hub) expert but I understand [submodules](https://blog.github.com/2016-02-01-working-with-submodules/) may provide an alternative to copying code to another repository (or possibly not, reading the caveats in that article). 

Ideally packages would be "repository aware" so prerequisites could download themselves automatically.... I have a mostly-working GitHub Package Manager that can do this, though it's currently restricted to prerequisites in the same repository.

**Comment by fxgallego** [comment]
Ok, could you share the GitHub package manager?

**Comment by rko281** [comment]
https://github.com/rko281/GitHubForDolphin

**Pull request merged**
